### PR TITLE
Ci improvement (continued)

### PR DESCRIPTION
**Pull request by InCogNiTo124**
Attempt no.2 for issue #84 #85

### CODE REVIEW

**Comment by Nukesor** [comment]
From what I understand, the co-authorship must be present on this commit of yours.
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

Simply adding a `Co-authored-by: name <name@example.com>` on the merge commit will probably do nothing, as the merge commit will be done by me/Github anyway.

Since I cannot change your commits, I assume you'll have to add this line to your commit message yourself.
You can get my commit Name + email address by looking at any of my commits via `git show`.

**Comment by InCogNiTo124** [comment]
I thought it was _you_ who had to put the coauthorshi note while merging. Let's see if this works out :smile:

**Comment by Nukesor** [comment]
This looks good :)

The commit now shows both icons and github detects both of us as authors:

[InCogNiTo124](https://github.com/Nukesor/comfy-table/commits?author=InCogNiTo124) and [Nukesor](https://github.com/Nukesor/comfy-table/commits?author=Nukesor) committed 31 minutes ago

**Comment by InCogNiTo124** [comment]
Thank you for this adventure and your patience! Hope to cooperate some more in the future :upside_down_face:

**Pull request merged**
